### ISSUE TITLE
Mudar o projeto para o Software Público

### ISSUE THREAD

**Issue by caduvieira** [culturagovbr/novosalic#2]
Levar os softwares para o gitlab do software público e manter esse aqui como mirror.

https://github.com/servicosgovbr/portal-de-servicos/issues/410

**Comment by nitaibezerra** [comment]
@caduvieira além das questões técnicas ainda é preciso registrar o código no INPI pra podermos chamá-lo de Software Público?

**Comment by caduvieira** [comment]
Pedi ajuda ao pessoal do software público @softwarepublico pois a IN que fala sobre isso não está disponível.

**Comment by caduvieira** [comment]
Alguem do spb entrou em contato?

**Comment by pettomartino** [comment]
Isso não tem haver com assuntos técnicos, favor procurar outras fontes para discutir esse assunto.

**Comment by caduvieira** [comment]
Nova IN para isso está em consulta pública e podem opinar nela.
http://www.participa.br/softwarepublico/minuta-da-instrucao-normativa-do-software-publico-software-de-governo-e-projeto-de-software/minuta-da-instrucao-normativa-do-software-publico-brasileiro-e-de-governo/minuta-da-instrucao-normativa

**Comment by pettomartino** [comment]
Quem pode fechar essa Issue?
